[workspace]
members = [
    "lib",
    "register",
    "withdraw",
    "transfer",
    "collateral_sufficiency",
    "repayment_history",
    "set_spender",
    "spender_transfer",
    "revoke_spender",
    "gadgets/assert_on_curve",
    "gadgets/commit",
    "gadgets/ecdh",
    "gadgets/vk_from_sk",
    "gadgets/encrypt_amount",
    "gadgets/poseidon_with_domain",
    "gadgets/sponge_squeeze_2",
]
